---
- name: Check if k3s is already installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_binary

- name: Install k3s server
  shell: |
    curl -sfL https://get.k3s.io | sh -s - server \
      --disable traefik \
      --write-kubeconfig-mode 644
  when: not k3s_binary.stat.exists

- name: Wait for node token to exist
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token
    state: present
    timeout: 60

- name: Read node token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Store token as fact
  set_fact:
    k3s_token: "{{ node_token.content | b64decode | trim }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['workers'] }}"

- name: Fetch kubeconfig to local machine
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~/.kube/config
    flat: yes

- name: Fix kubeconfig server address
  delegate_to: localhost
  become: false
  replace:
    path: ~/.kube/config
    regexp: 'https://127\.0\.0\.1:6443'
    replace: "https://51.20.35.120:6443"