---
- name: Harden all nodes
  hosts: all
  become: true
  roles:
    - hardening

- name: Set up k3s control plane
  hosts: control_plane
  become: true
  roles:
    - k3s-server

- name: Join workers to cluster
  hosts: workers
  become: true
  roles:
    - k3s-agent